### ISSUE TITLE
Add license file to repository.

### ISSUE THREAD

**Issue by rmetzger** [SolaceLabs/solace-integration-guides#6]
While checking the flink sample code in the repository, I didn't find any license for it.

It would be nice if you could add that to the repo :)

The reason why I've looked up the license was, that I was evaluating whether you can contribute the Flink JMS connector code to the `apache/bahir-flink` repository.

**Comment by mdspielman** [comment]
Good suggestion. That's an oversight. I'll add the licence soon. We plan to use Apache 2. Would that work for you?

**Comment by rmetzger** [comment]
Yes.

I have to admit that I might have been overhasty / over excited over your code. There's already an ActiveMQ connector in Bahir, and I belive your code and ActiveMQ both support the JMS standard.
Are there any advantages of your impl over ActiveMQ?

**Comment by mdspielman** [comment]
We believe there are many advantages to our JMS. Perhaps we could add Solace JMS next to ActiveMQ. If you'd like to discus Solace JMS and ActiveMQ, feel free to email me (mark.spielman@solace.com) since that is somewhat orthogonal to the issue you raised which I will resolve.

**Comment by mdspielman** [comment]
License agreement added.
